### ISSUE TITLE
Cannot install hvac-enact sample

### ISSUE THREAD

**Issue by mzwtjp** [webosose/meta-agl-lge#2]
I just built meta-agl-lge on top of AGL eel branch.
Among the four wgt package provided in this recipe, hvac-react.wgt fails to be installed.

>root@intel-corei7-64:~# /etc/agl-postinsts/10-afm-widget-examples.sh 
>{ "added": "webapps-annex@0.0" }
>Error org.freedesktop.DBus.Error.Failed: "installation failed"

journal log says afm-system-daemon says it could not find config.xml, and I cannot find it in hvac-react.wgt.

>Jun 28 01:35:18 intel-corei7-64 afm-system-daemon[1030]:  ERROR: can't open config file config.xml [/usr/src/debug/af-main/eel+gitAUTOINC+83ac3d4fd8-r0/git/src/wgt-config.c:95]

The other 3 wgts could be installed witout error.

>root@intel-corei7-64:~# . ./foo.sh
>{ "added": "webapps-annex@0.0" }
>{ "added": "webapps-memory-match@1.1" }
>{ "added": "webapps-youtube@1.0" }
>root@intel-corei7-64:~#

**Comment by mzwtjp** [comment]
FYI.
By adding config.xml (copied from youtube-agl.wgt) to the package, webapps-hvac@1.0 installed successfully.

**Comment by zhani** [comment]
@mzwtjp Thanks for pointing this out. Config.xml is now added
https://github.com/webosose/meta-agl-lge/commit/ae1c80080b04265223b5199df65950f21ae7bc4f
