### ISSUE TITLE
Annex sample does not respond

### ISSUE THREAD

**Issue by mzwtjp** [webosose/meta-agl-lge#3]
I just built meta-agl-lge on top of AGL eel branch.
On AGL homescreen I can see "Annex" icon and if I choose it the app is invoked.

But I can see following issues.
I have not looked into details, and not sure if this is AGL homescreen issue or the app problem.

1) Music played once at the first launch.  But not played on 2nd or after attempt.

Operation: press Home to insactivate app and then press "Annex" again.
Expectation: Should the music played everytime app is invoked?

2) At first launch, Annex app is displayed in 1/2 half of the AGL homescreen app area.  But on 2nd and after attemt, it is displayed whole area of AGL homescreen app area.

Expectation: Should the app displayed full area all the time?

3) Annex app does not seem to interact with my touch on "1 Player Game", "2 Player Game", "How to Play" and "Exit".

I can see a few logs in journal.  Not sure if this is from app or AGL framework though.
(Perhaps app is not receiving touch events?)

>Jun 28 02:19:48 intel-corei7-64 afbd-homescreen-2017@0.1[1811]: "HomeScreen"
>Jun 28 02:19:48 intel-corei7-64 afbd-webapps-annex@0.0[2264]: Got Event_Inactive
>Jun 28 02:19:48 intel-corei7-64 afbd-webapps-annex@0.0[2264]: Got Event_Invisible
>Jun 28 02:19:48 intel-corei7-64 afbd-webapps-annex@0.0[2264]: Got Event_Visible
>Jun 28 02:19:49 intel-corei7-64 afbd-webapps-annex@0.0[2264]: Event_TapShortcut <Annex>
>Jun 28 02:19:49 intel-corei7-64 afbd-webapps-annex@0.0[2264]: Activesurface WebApp-1024
>Jun 28 02:19:49 intel-corei7-64 afbd-webapps-annex@0.0[2264]: Got Event_SyncDraw
>Jun 28 02:19:49 intel-corei7-64 afbd-webapps-annex@0.0[2264]: Got Event_Visible
>Jun 28 02:19:49 intel-corei7-64 afbd-homescreen-2017@0.1[1811]: "WebApp-1024"
>Jun 28 02:19:49 intel-corei7-64 afbd-webapps-annex@0.0[2264]: Got Event_Active
>Jun 28 02:19:49 intel-corei7-64 afbd-webapps-annex@0.0[2264]: Got Event_FlushDraw

**Comment by mzwtjp** [comment]
It seems "youtube" and "chromium53-browesr-service" also do not respond to my tapping.

**Comment by mzwtjp** [comment]
![dsc_1057](https://user-images.githubusercontent.com/16159690/42011086-c31ce748-7acc-11e8-9e6e-43f8b1303f32.JPG)

**Comment by zhani** [comment]
Annex issues fixed. See
https://github.com/webosose/meta-agl-lge/commit/36de191c14c251a34facf7a2758e218756ffbe11
https://github.com/webosose/meta-agl-lge/commit/729b169ef5ec124eed2ece8852ff92859044c358

Also make sure you are using eel stable 5.0.3 version. Updated readme regarding that
https://github.com/webosose/meta-agl-lge/commit/ad48b2c26e8c32550161a5dd4571cb3e36a924e1
