### ISSUE TITLE
hvac-enact.wgt too large

### ISSUE THREAD

**Issue by mzwtjp** [webosose/meta-agl-lge#5]
I can see this wgt's size is 9MB.
I understand that this is bcause the package incudes the whole nodejs files, and this is just a sample.

But nontheless, I think it is not a good situation that every demo wgt comes with a set of nodejs, etc. independently.

**Comment by zhani** [comment]
For now we are not including enact/nodejs as system libs so for demo purposes each app includes libs it needs
